import { ThemeStyle, ThemeColors } from '../types';

export const THEMES: Record<ThemeStyle, ThemeColors & { name: string; description: string }> = {
  SARAJEVO_SUNSET: {
    name: 'Sarajevo Sunset (Cover Art)',
    description: 'Solar Gold Core, Fiery Orange Flare & Deep Balkan Twilight Magenta',
    primary: '#ffe600',
    secondary: '#ff5500',
    accent: '#ff0055',
    background: '#090206',
    wave: '#ffaa00',
    matrix: '#ff3300',
    textGlow: '#fff3c0',
    spectrumGradient: ['#ff0055', '#ff5500', '#ffe600'],
  },
  BALKAN_NEON_CYBER: {
    name: 'Balkan Neon Cyber',
    description: 'Electric Cyan (#00f0ff), Glitchcore Hot Pink (#ff0077) & Ultraviolet',
    primary: '#00f0ff',
    secondary: '#ff0077',
    accent: '#9900ff',
    background: '#04020a',
    wave: '#00f0ff',
    matrix: '#ff0077',
    textGlow: '#ffffff',
    spectrumGradient: ['#ff0077', '#9900ff', '#00f0ff'],
  },
  ACID_EMERALD: {
    name: 'Acid Emerald Glitch',
    description: 'Toxic 303 Emerald, High-Voltage Amber & Glitch Matrix Stream',
    primary: '#00ff66',
    secondary: '#ffe600',
    accent: '#ff0055',
    background: '#020d04',
    wave: '#00ff66',
    matrix: '#00ff41',
    textGlow: '#ccffcc',
    spectrumGradient: ['#00ff41', '#00ff66', '#ffe600'],
  },
  QUANTUM_VIOLET_SUN: {
    name: 'Quantum Violet Sun',
    description: 'Deep Cosmic Ultraviolet, Strobe Cyan & Supernova Gold',
    primary: '#b026ff',
    secondary: '#00f3ff',
    accent: '#ffcc00',
    background: '#07020f',
    wave: '#00f3ff',
    matrix: '#b026ff',
    textGlow: '#f0d0ff',
    spectrumGradient: ['#ff007f', '#b026ff', '#00f3ff'],
  },
  MONOCHROME_BRUTALIST: {
    name: 'Monochrome Brutalist',
    description: 'Stark High-Contrast Noir, Cold White Phosphor & Severe Glitch Noise',
    primary: '#ffffff',
    secondary: '#888888',
    accent: '#ffffff',
    background: '#000000',
    wave: '#ffffff',
    matrix: '#aaaaaa',
    textGlow: '#ffffff',
    spectrumGradient: ['#444444', '#aaaaaa', '#ffffff'],
  },
  CYBERPUNK: {
    name: 'Miku Vajfuša Cyberpunk',
    description: 'Iconic Miku Teal, Glitchcore Magenta, and CRT Scanlines',
    primary: '#39c5bb',
    secondary: '#ff00ff',
    accent: '#ff3300',
    background: '#050505',
    wave: '#00ffcc',
    matrix: '#00ff41',
    textGlow: '#ffffff',
    spectrumGradient: ['#00ffcc', '#39c5bb', '#ff00ff'],
  },
  ACID_MATRIX: {
    name: 'Acid Matrix 303',
    description: 'Toxic Emerald, High-Voltage Amber, and Infinite Matrix Stream',
    primary: '#00ff66',
    secondary: '#ffe600',
    accent: '#ff0055',
    background: '#020d04',
    wave: '#00ff66',
    matrix: '#00ff41',
    textGlow: '#ccffcc',
    spectrumGradient: ['#00ff41', '#00ff66', '#ffe600'],
  },
  TOKYO_VIOLET: {
    name: 'Tokyo Violet Laser',
    description: 'Deep Ultraviolet, Electric Cyan, and Neon Laser Strobe',
    primary: '#b026ff',
    secondary: '#00f3ff',
    accent: '#ff007f',
    background: '#07020f',
    wave: '#00f3ff',
    matrix: '#b026ff',
    textGlow: '#f0d0ff',
    spectrumGradient: ['#00f3ff', '#b026ff', '#ff007f'],
  },
  MONOCHROME: {
    name: 'Monochrome Brutalist (Classic)',
    description: 'Stark High-Contrast Noir and Cold White Phosphor',
    primary: '#ffffff',
    secondary: '#888888',
    accent: '#ffffff',
    background: '#000000',
    wave: '#ffffff',
    matrix: '#aaaaaa',
    textGlow: '#ffffff',
    spectrumGradient: ['#444444', '#aaaaaa', '#ffffff'],
  },
  SOLAR_FLARE: {
    name: 'Molten Solar Flare',
    description: 'Volcanic Magma, Molten Gold Amber, and Fiery Corona Shockwaves',
    primary: '#ffaa00',
    secondary: '#ff003c',
    accent: '#ffe600',
    background: '#0c0401',
    wave: '#ffaa00',
    matrix: '#ff5500',
    textGlow: '#fff3d0',
    spectrumGradient: ['#ff003c', '#ff5500', '#ffaa00'],
  },
};
